### PR TITLE
Try to fail

### PR DESCRIPTION
**Pull request by orionw**
Previous failing builds did not fail on CI.  This makes CI fail if the tests fail.

### CODE REVIEW

**Comment by epeters3** [comment]
Hi @orionw, would you be willing to clean up this PR if it’s not too much trouble, so it only includes the commits that fix the CI issue? I.e. so it doesn’t include the `update-D3M-docker` commits, so those aren’t included twice on the git history and we don’t get any accidental changes or reverts leaking in hidden among these other commits?

**Comment by orionw** [comment]
Sure I can merge in develop.  Did you rebased the previous one? Usually it would just show the updates since the previous one was merged in since they were the same branch originally.

**Comment by epeters3** [comment]
Thank you! Yes I probably rebased it. I like rebasing since then there are no "merged..." commits in the git history except when PRs are merged. I hope I didn't mess it up.

**Comment by epeters3** [comment]
Another reason rebasing is nice is because you can use it to rewrite your commit history and "fixup" any commits that were just test commits or commits addressing things you forgot to add in your previous commit, etc.

**Comment by orionw** [comment]
@epeters3 I merged in develop to this branch and it only has the few lines of changes.  Let me know what you think.

**Comment by epeters3** [comment]
Looks great @orionw! A little bash magic.

**Pull request merged**
